# Generated by Django 5.0.6 on 2024-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(null=True),
        ),
    ]
