# Generated by Django 5.0.6 on 2024-06-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entidades', '0003_alter_prestamo_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='lector',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Lector/Lectora', 'verbose_name_plural': 'Lectores'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['nombre', 'autor'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
